apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  releaseName: gatekeeper
  chart:
    spec:
      version: "3.20.1"
      chart: gatekeeper/gatekeeper
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
  interval: 50m
  install:
    remediation:
      retries: 1
