apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radius-system
resources:
  - ../../base/radius
  - ../../../radius/recipes/radius
  - ../../../radius/recipes-repos/radius
  - ../../../radius/resources-types/radius
