apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../useCases/proofKustomizationNSOverride/podinfoNSNotOverride
  - ../../useCases/proofKustomizationNSOverride/podinfoNSOverride
