apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helloworld
resources:
  - namespace.yaml
  - application.yaml

configMapGenerator:
  - name: values
    files:
      - values.yaml=default-values.yaml

generatorOptions:
  disableNameSuffixHash: true
