apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: components
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/crds/components
  prune: true
  wait: true
  timeout: 5m0s
  dependsOn:
    - name: crds

