apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-providers
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: apps
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./providers/dev
  prune: true
  wait: true
  timeout: 5m0s
