apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
spec:
  secretName: test-cert-tls
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: thatdomain.com
  dnsNames:
    - thatdomain.com

