apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: radius-recipes
  namespace: radius-system
spec:
  interval: 1m
  url: https://github.com/jjnasarabias/recipes.git
  ref:
    branch: main
  secretRef:
    name: jjnasarabias-git-repo
