apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../assign.yaml

namePrefix: test2-

patches:
  - target:
      kind: Assign
    patch: |-
      - op: replace
        path: /spec/location
        value: spec.template.metadata.labels.xpto.test.com/test2
      - op: replace
        path: /spec/parameters/assign/fromMetadata/field
        value: spec.template.metadata.labels.xpto.test.com/test2