apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: copy-workload-label-to-pod-template
spec:
  applyTo:
    - groups: ["apps"]
      versions: ["v1"]
      kinds: ["Deployment", "StatefulSet", "DaemonSet"]
  match:
    scope: Cluster
#    excludedNamespaces: "*-system"
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
  location: "spec.template.metadata.labels.xpto.test.com/test"
  parameters:
    assign:
      fromMetadata:
        field: "metadata.labels.xpto.test.com/test"
        obj: namespace