apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./helm-release.yaml

configMapGenerator:
  - name: values-for-gatekeeper-assigners
    namespace: flux-system
    files:
      - values.yaml=values.yaml

configurations:
  - kustomize-values.yaml

