apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda-system
spec:
  releaseName: keda
  chart:
    spec:
      version: "2.18.0"
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
  interval: 50m
  install:
    remediation:
      retries: 1
