apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vela-system
resources:
  - ../../base/vela

patches:
  - path: values-patch.yaml
    target:
      name: values
      kind: ConfigMap
      namespace: vela-system
