apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - namespace.yaml
configMapGenerator:
  - name: helmrelease-values-cert-manager
    namespace: flux-system
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizevalues.yaml
